### ISSUE TITLE
Gandi Support

### ISSUE THREAD

**Issue by 42atomys** [42Atomys/dns-updater#2]
Manque le support de Gandi mais ouais c'est propre.

_Originally posted by @rgaiffe in https://github.com/42Atomys/dns-updater/issues/1#issuecomment-1026978940_

**Comment by 42atomys** [comment]
Issue: https://gitlab.com/Atomys/dns-updater/-/issues/1

**Comment by jgengo** [comment]
Je dirais que ca manque de google.domains mtn! mais j'ai espoir que @rgaiffe le fasse avant meme que j'ai fini d'ecrire ce commentaire

**Comment by rgaiffe** [comment]
Soon TM
